baseURL = 'https://pablo2909.github.io/pauljeha/'
languageCode = 'en-us'
title = 'Paul Jeha'
theme = 'archie'

#[params]
##mode="auto"
##useCDN=false
#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

#relativeURLs = true
#canonifyURLs = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pablo2909"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  katex = true


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/jeha_paul"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4




